name: Pull Requests

on:
  pull_request: {}

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/verification
      with:
        tag: ${{ github.sha }}
        
