name: Tag

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: verification
        uses: ./.github/actions/verification
        with:
          tag: ${{ github.sha }}
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          force-bump-patch-version: true
      - name: check docker
        run: |
          docker images
      - name: check sha
        run: |
          echo "${{ github.sha }}"
