name: Verification

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      push:
        required: true
        type: boolean

jobs:
  # Runs the linter
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - run: go version
      # Lint 
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.45.2
      - name: Unit Tests
        run:  go test -v --short --race -json -coverprofile=coverage.out ./... > unit-test.json
      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annoations@v0.5.1
        with:
          test-results: unit-test.json
      - name: 'Build image'
      - run: |
          docker build . -t testing:${{ inputs.tag }}
          ${{ inputs.push }} && echo "Pushing"

